### ISSUE TITLE
feature: put some command options of `kpm` into `kcl.mod`

### ISSUE THREAD

**Issue by zong-zhe** [KusionStack/kpm#78]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The kpm command contains parameters such as `--input`, `--kcl_args`, etc. Put these parameters into `kcl.mod` to simplify the commands that users need to type in the shell.

**Describe the feature you'd like:**

The content of  `--kcl_args` in `kcl.mod`.
```
[package]
name = "xxx"
edition = "0.0.1"
version = "0.0.1"

[dependencies]
xxx = "0.0.1"

[profile]
# -- input, There is currently no support for describing external package files here, 
# so the paths in 'entries' are relative to the 'kcl.mod' file path of the current package.
entries = ["main.k", "xxx/xxx/dir"]

# --kcl-args
options = ["a=b", "b=c"]
overrides = ["a=b", "b=c"]
disable_none = true
sort_key = true
settings = ["xxx/xxx/kcl.yaml"]
```

**Describe alternatives you've considered:**

rust's implementation `cargo.toml` is referenced here

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Peefy** [comment]
I suggest that the entry directly use the kcl.yaml file/KCL file/dir to shrink the user interface as much as possible and avoid synchronizing the configuration of kpm and kcl.
